version: 0.0
os: linux

files:
  - source: /
    destination: /var/cdk-app/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/create_or_update_service.sh
      timeout: 300
      runas: root
  ApplicationStart:
      - location: scripts/runas.sh
        timeout: 300